#agents:
 # - id: common_agent
  #  name: CommonAgent
   # description: Handles general questions about the company.
    #module: agents.common_agent
    #class: CommonAgent
    #active: true
    #index_path: "data/faiss_index/common_agent.index"
    #document_store_path: "data/faiss_index/documents.pkl"


#common_agent:
 # name: "CommonAgent"
  #index_path: "data/faiss_index/common_agent.index"
  #document_store_path: "data/faiss_index/documents.pkl"

agents:
  - name: common_agent
    config:
      greeting: "Hi, how can I help you today?"

  - name: docs_agent

  - name: itsm_agent

  - name: devops_agent
