#agents:
 # - id: common_agent
  #  name: CommonAgent
   # description: Handles general questions about the company.
    #module: agents.common_agent
    #class: CommonAgent
    #active: true
    #index_path: "data/faiss_index/common_agent.index"
    #document_store_path: "data/faiss_index/documents.pkl"


#common_agent:
 # name: "CommonAgent"
  #index_path: "data/faiss_index/common_agent.index"
  #document_store_path: "data/faiss_index/documents.pkl"

#agents:
 # - name: common_agent
  #  config:
   #   greeting: "Hi, how can I help you today?"

  #- name: docs_agent

  #- name: itsm_agent

 # - name: devops_agent

agents:
  - name: common_agent
    type: common
    config:
      greeting: "Hi, how can I help you today?"

  - name: docs_agent
    type: docs

  - name: itsm_agent
    type: itsm

  - name: devops_agent
    type: devops
    config:
      etl_script: "scripts/run_etl.py"
      db_sync_script: "scripts/db_sync.py"
      dashboard_script: "scripts/update_dashboard.py"
      kpi_path: "data/kpi_report.json"

  - name: hr_agent
    type: hr

  - name: summarizer_agent
    type: summarizer

  - name: multi_agent
    type: multi

